version: '3'
services:
  mongo:
    image: mongo:4.4.4
    container_name: top-api-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db
    command: --wiredTigerCacheSizeGB 1.
  backend:
    container_name: top-api-backend
    build:
      context: ./
    depends_on:
      - mongo:4.4.4
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=mongo
