version: '3'
services:
  top.api:
    image: docker.pkg.github.com/Eltach00/new-top-api/new-top-api:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
